# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-10 23:10
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField(verbose_name='fecha de inicio')),
                ('end', models.DateField(verbose_name='Fecha de finalización')),
            ],
            options={
                'verbose_name': 'curso',
            },
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
                ('years', models.IntegerField(verbose_name='número de años')),
            ],
            options={
                'verbose_name': 'carrera',
            },
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(verbose_name='calificación')),
                ('report', models.FileField(upload_to='', verbose_name='informe del estudiante')),
                ('tutor_report', models.FileField(upload_to='', verbose_name='informe del tutor')),
            ],
            options={
                'verbose_name': 'participación',
                'verbose_name_plural': 'participaciones',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
                ('description', models.CharField(max_length=200, verbose_name='descripción')),
                ('report', models.FileField(upload_to='', verbose_name='informe del tutor')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practicas.Course')),
            ],
            options={
                'verbose_name': 'proyecto',
            },
        ),
        migrations.CreateModel(
            name='RegisteredStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=200, verbose_name='grupo')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practicas.Course')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practicas.Major')),
            ],
            options={
                'verbose_name': 'estudiante registrado',
                'verbose_name_plural': 'estudiantes registrados',
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(verbose_name='prioridad')),
                ('checked', models.BooleanField(verbose_name='confirmación del tutor')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practicas.Project')),
                ('reg_student',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practicas.RegisteredStudent')),
            ],
            options={
                'verbose_name': 'solicitud',
                'verbose_name_plural': 'solicitudes',
            },
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('students_count', models.IntegerField(verbose_name='cantidad de estudiantes')),
                ('year', models.IntegerField(verbose_name='año')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practicas.Major')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practicas.Project')),
            ],
            options={
                'verbose_name': 'requisito',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                'user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'estudiante',
            },
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category',
                 models.CharField(choices=[('DR', 'Doctor'), ('MSC', 'Master'), ('LIC', 'Licenciado')], max_length=3,
                                  verbose_name='categoría científica')),
                ('job', models.CharField(max_length=200, verbose_name='puesto')),
                (
                'user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'tutores',
            },
        ),
        migrations.CreateModel(
            name='Workplace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200, verbose_name='dirección')),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
                ('phone', models.IntegerField(verbose_name='teléfono')),
            ],
            options={
                'verbose_name': 'centro de trabajo',
                'verbose_name_plural': 'centros de trabajo',
            },
        ),
        migrations.AddField(
            model_name='tutor',
            name='workplace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practicas.Workplace'),
        ),
        migrations.AddField(
            model_name='registeredstudent',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practicas.Student'),
        ),
        migrations.AddField(
            model_name='project',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practicas.Tutor'),
        ),
        migrations.AddField(
            model_name='participation',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practicas.Project'),
        ),
        migrations.AddField(
            model_name='participation',
            name='reg_student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='practicas.RegisteredStudent'),
        ),
    ]
