# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-10 23:16
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('practicas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participation',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practicas.Project',
                                    verbose_name='proyecto'),
        ),
        migrations.AlterField(
            model_name='participation',
            name='reg_student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='practicas.RegisteredStudent',
                                       verbose_name='estudiante registrado'),
        ),
        migrations.AlterField(
            model_name='project',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practicas.Course',
                                    verbose_name='curso'),
        ),
        migrations.AlterField(
            model_name='registeredstudent',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practicas.Course',
                                    verbose_name='curso'),
        ),
        migrations.AlterField(
            model_name='registeredstudent',
            name='major',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practicas.Major',
                                    verbose_name='carrera'),
        ),
        migrations.AlterField(
            model_name='registeredstudent',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practicas.Student',
                                    verbose_name='estudiante'),
        ),
        migrations.AlterField(
            model_name='request',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practicas.Project',
                                    verbose_name='proyecto'),
        ),
        migrations.AlterField(
            model_name='request',
            name='reg_student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practicas.RegisteredStudent',
                                    verbose_name='estudiante registrado'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='major',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practicas.Major',
                                    verbose_name='carrera'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practicas.Project',
                                    verbose_name='proyecto'),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL,
                                       verbose_name='usuario'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL,
                                       verbose_name='usuario'),
        ),
    ]
