# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-10 23:16
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('practicas', '0002_auto_20160410_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='workplace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practicas.Workplace',
                                    verbose_name='centro de trabajo'),
        ),
    ]
