# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-11 05:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('practicas', '0004_auto_20160411_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participation',
            name='report',
            field=models.FileField(blank=True, upload_to='', verbose_name='informe del estudiante'),
        ),
        migrations.AlterField(
            model_name='participation',
            name='tutor_report',
            field=models.FileField(blank=True, upload_to='', verbose_name='informe del tutor'),
        ),
        migrations.AlterField(
            model_name='project',
            name='report',
            field=models.FileField(blank=True, upload_to='', verbose_name='informe del tutor'),
        ),
    ]
