# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-11 20:40
from __future__ import unicode_literals

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('practicas', '0005_auto_20160411_0108'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': [], 'verbose_name': 'proyecto'},
        ),
        migrations.AddField(
            model_name='course',
            name='practice_end',
            field=models.DateField(default=datetime.datetime(2016, 4, 11, 20, 39, 46, 817623, tzinfo=utc),
                                   verbose_name='fecha de finalización de las prácticas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='practice_start',
            field=models.DateField(default=datetime.datetime(2016, 4, 11, 20, 40, 5, 513132, tzinfo=utc),
                                   verbose_name='fecha de inicio de las prácticas'),
            preserve_default=False,
        ),
    ]
