# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-11 23:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('practicas', '0006_auto_20160411_1640'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'proyecto'},
        ),
    ]
