# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-12 21:00
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('practicas', '0007_auto_20160411_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='major',
            name='years',
            field=models.IntegerField(validators=[
                django.core.validators.MinValueValidator(1, message='Toda carrera debe durar más de 1 año.')],
                                      verbose_name='número de años'),
        ),
    ]
