# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-12 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('practicas', '0010_auto_20160412_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='priority',
            field=models.PositiveIntegerField(verbose_name='prioridad'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='students_count',
            field=models.PositiveIntegerField(verbose_name='cantidad de estudiantes'),
        ),
    ]
