# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-12 21:46
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('practicas', '0012_auto_20160412_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='students_count',
            field=models.IntegerField(validators=[
                django.core.validators.MinValueValidator(1, 'En el proyecto debe participar al menos 1 estudiante.')],
                                      verbose_name='cantidad de estudiantes'),
        ),
    ]
