# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-13 03:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('practicas', '0013_auto_20160412_1746'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'permissions': [('student_permissions', 'Tiene permisos de estudiante')],
                     'verbose_name': 'estudiante'},
        ),
        migrations.AlterModelOptions(
            name='tutor',
            options={'permissions': [('tutor_permissions', 'Tiene permisos de tutor')],
                     'verbose_name_plural': 'tutores'},
        ),
    ]
