# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-13 05:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('practicas', '0014_auto_20160412_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(verbose_name='descripción'),
        ),
    ]
