# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-13 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('practicas', '0016_registeredstudent_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(default='a'),
            preserve_default=False,
        ),
    ]
