# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-13 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('practicas', '0017_project_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='checked',
            field=models.BooleanField(default=False, verbose_name='confirmación del tutor'),
        ),
    ]
