# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-13 20:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('practicas', '0018_auto_20160413_1556'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='request',
            unique_together=set([('reg_student', 'project')]),
        ),
    ]
